/* EVEN FIBONACCI NUMBERS */

/* 
  Each new term in the Fibonacci sequence is generated by adding the previous 
  two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed 
  four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

#define FOUR_MIL 4000000

int solution(void);

int main(void)
{
  printf("%d", solution());
  return 0;
}

int solution(void)
{
  int sum = 0;

  int curr = 2;
  int prev = 1;

  while (curr <= FOUR_MIL)
  {
    if (curr % 2 == 0)
      sum += curr;

    int next = curr + prev;
    prev = curr;
    curr = next;
  }

  return sum;
}